### ISSUE TITLE
大佬 这个仓库是干啥的？

### ISSUE THREAD

**Issue by fusang1337** [shilapi/YunduoApkModify#1]

**Comment by shilapi** [comment]
云朵原生应用的修改，目前暂时就折腾出改分屏这一种玩法

**Comment by fusang1337** [comment]
谢谢回复，意思是可以把分屏APP替换成其他的是吧，有没有可能使用carlife呢？

**Comment by shilapi** [comment]
参考我readme里面写的carplay部分，换CarPlay盒子就行。无盒子的方案还没出来。
